name: proyectos_matchy
description: Aplicación Matchy en Flutter
publish_to: "none"

# ✅ 1. CAMBIO DE VERSIÓN (Subimos a 1.0.1 y Build 11 para asegurar)
version: 1.0.1+19

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  url_launcher: ^6.3.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.2
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# ✅ 2. CONFIGURACIÓN DEL ÍCONO
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  # 🟣 AQUÍ ESTÁ EL TRUCO: El fondo morado se genera por código
  adaptive_icon_background: "#7E208E"
  remove_alpha_ios: true