name: proyectos_matchy

description: Aplicación Matchy en Flutter
publish_to: "none"

version: 1.0.0+10

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # FIREBASE CORE
  firebase_core: ^3.15.2

  # AUTH
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1

  # FIRESTORE
  cloud_firestore: ^5.6.12

  # STORAGE (fotos reales desde Firebase Storage)
  firebase_storage: ^12.4.10

  # Abrir enlaces externos
  url_launcher: ^6.3.0

  # Localización ES
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Estado global Matchy
  flutter_riverpod: ^2.6.1

  # Persistencia local
  shared_preferences: ^2.3.2

  # Cámara y galería
  image_picker: ^1.0.7

  # 🔥 NUEVO: Visor de fotos (Zoom y Pan)
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"
  remove_alpha_ios: true